In [ ]:
10-03-2026

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
conn = sqlite3.connect("company.db")

In [ ]:
conn.execute("""
CREATE TABLE employee(
empid INTEGER,
name TEXT,
salary INTEGER,
dept TEXT
)
""")

In [ ]:
conn.execute("INSERT INTO employee VALUES (1,'Rahul',50000,'IT')")
conn.execute("INSERT INTO employee VALUES (2,'Aman',65000,'HR')")
conn.execute("INSERT INTO employee VALUES (3,'Priya',70000,'IT')")
conn.execute("INSERT INTO employee VALUES (4,'Neha',45000,'Finance')")

In [ ]:
pd.read_sql_query("SELECT * FROM employee", conn)

   empid   name  salary     dept
0      1  Rahul   50000       IT
1      2   Aman   65000       HR
2      3  Priya   70000       IT
3      4   Neha   45000  Finance

In [ ]:
pd.read_sql_query("""
SELECT name, salary
FROM employee
WHERE salary > (SELECT AVG(salary) FROM employee)
""", conn)

    name  salary
0   Aman   65000
1  Priya   70000

In [ ]:
SELECT name, salary
FROM employee
WHERE salary > (SELECT AVG(salary) FROM employee);

SyntaxError: invalid syntax (2486698066.py, line 1)

In [ ]:
pd.read_sql_query("""
SELECT name
FROM employee
WHERE dept IN (
SELECT dept FROM employee WHERE salary > 60000
)
""", conn)

    name
0  Rahul
1   Aman
2  Priya

In [ ]:
pd.read_sql_query("""
SELECT name, salary
FROM employee
WHERE salary > (SELECT AVG(salary) FROM employee)
""", conn)

    name  salary
0   Aman   65000
1  Priya   70000

In [ ]:
pd.read_sql_query("""
SELECT name,
(SELECT AVG(salary) FROM employee) AS Avg_sal
FROM employee
""", conn)

    name  Avg_sal
0  Rahul  57500.0
1   Aman  57500.0
2  Priya  57500.0
3   Neha  57500.0

In [ ]:
conn.execute("""
CREATE TABLE customers(
cus_id INTEGER,
cus_name TEXT,
location TEXT
)
""")

In [ ]:
conn.execute("INSERT INTO customers VALUES (101,'Akash','India')")
conn.execute("INSERT INTO customers VALUES (102,'Vaishnavi','Srilanka')")
conn.execute("INSERT INTO customers VALUES (103,'Thakur','Spain')")
conn.execute("INSERT INTO customers VALUES (104,'Abishek','Australia')")

In [ ]:
conn.execute("""
CREATE TABLE products(
prod_id INTEGER,
prod_name TEXT,
price INTEGER
)
""")

In [ ]:
conn.execute("INSERT INTO products VALUES (1,'Laptop',70000)")
conn.execute("INSERT INTO products VALUES (2,'Mobile',20000)")
conn.execute("INSERT INTO products VALUES (3,'Headphones',3000)")
conn.execute("INSERT INTO products VALUES (4,'Tablet',25000)")

In [ ]:
conn.execute("""
CREATE TABLE orders(
order_id INTEGER,
cus_id INTEGER,
prod_id INTEGER,
amount INTEGER
)
""")

In [ ]:
conn.execute("INSERT INTO orders VALUES (1,101,1,70000)")
conn.execute("INSERT INTO orders VALUES (2,102,2,20000)")
conn.execute("INSERT INTO orders VALUES (3,101,3,3000)")

In [ ]:
pd.read_sql_query("""
SELECT cus_name
FROM customers
WHERE cus_id IN (
SELECT cus_id FROM orders
)
""", conn)

    cus_name
0      Akash
1  Vaishnavi

In [ ]:
pd.read_sql_query("""
SELECT prod_name
FROM products
WHERE prod_id IN (
SELECT prod_id FROM orders
)
""", conn)

    prod_name
0      Laptop
1      Mobile
2  Headphones

In [ ]:
pd.read_sql_query("""
SELECT prod_name
FROM products
WHERE prod_id NOT IN (
SELECT prod_id FROM orders
)
""", conn)

  prod_name
0    Tablet

In [ ]:
pd.read_sql_query("""
SELECT prod_name
FROM products
WHERE price = (
SELECT MAX(price) FROM products
)
""", conn)

  prod_name
0    Laptop

In [ ]:
pd.read_sql_query("""
SELECT *
FROM orders
WHERE amount > (
SELECT AVG(amount) FROM orders
)
""", conn)

   order_id  cus_id  prod_id  amount
0         1     101        1   70000

In [ ]:
pd.read_sql_query("""
SELECT prod_name, price
FROM products
WHERE price > (
SELECT AVG(price) FROM products
)
""", conn)

  prod_name  price
0    Laptop  70000

In [ ]:
conn.execute("""
CREATE TABLE Employee_Salary_Dataset(
ID INTEGER,
Age INTEGER,
Salary INTEGER,
Experience_Years INTEGER
)
""")

In [ ]:
conn.execute("INSERT INTO Employee_Salary_Dataset VALUES (34,28,60000,5)")
conn.execute("INSERT INTO Employee_Salary_Dataset VALUES (12,30,45000,3)")
conn.execute("INSERT INTO Employee_Salary_Dataset VALUES (56,35,80000,8)")

In [ ]:
pd.read_sql_query("SELECT * FROM Employee_Salary_Dataset", conn)

   ID  Age  Salary  Experience_Years
0  34   28   60000                 5
1  12   30   45000                 3
2  56   35   80000                 8

In [ ]:
pd.read_sql_query("SELECT Age, Salary FROM Employee_Salary_Dataset", conn)

   Age  Salary
0   28   60000
1   30   45000
2   35   80000

In [ ]:
pd.read_sql_query("SELECT MAX(Salary) AS max_salary FROM Employee_Salary_Dataset", conn)

   max_salary
0       80000

In [ ]:
pd.read_sql_query("SELECT MIN(Salary) AS min_salary FROM Employee_Salary_Dataset", conn)

   min_salary
0       45000

In [ ]:
pd.read_sql_query("SELECT AVG(Salary) AS avg_salary FROM Employee_Salary_Dataset", conn)

     avg_salary
0  61666.666667

In [ ]:
pd.read_sql_query("SELECT * FROM Employee_Salary_Dataset WHERE Salary > 50000", conn)

   ID  Age  Salary  Experience_Years
0  34   28   60000                 5
1  56   35   80000                 8

In [ ]:
pd.read_sql_query("SELECT ID, Experience_Years FROM Employee_Salary_Dataset WHERE ID = 34", conn)

   ID  Experience_Years
0  34                 5